### ISSUE TITLE
Request for Access to Original JavaScript Source for Customizing Prompt Structure

### ISSUE THREAD

**Issue by harshkumarchourasia** [mitenmit/gpt#1]
Hello,

Firstly, I'd like to express my gratitude for making this project available as open source. It's a wonderful resource, and I appreciate the effort that has gone into its development.

I'm currently working on a customization that involves altering the default prompt structure to better suit the needs of my project. To achieve this, I believe I would need access to the original, non-compiled JavaScript source code.
Would it be possible to share the original JavaScript source files, or could you guide me on how I might be able to make these modifications using the currently available resources? My goal is to tailor the prompt structure to enhance the user experience for a specific use case.

Thank you for considering my request. I'm looking forward to your guidance and am happy to contribute back any modifications or improvements that could benefit the project as a whole.

Best regards,
Harsh

**Comment by mitenmit** [comment]
Hi,
 
Thanks for your interest :) 
I am planing to opensource the code in the near future. It is currently written in ClojureScript. 
In the meantime, in v0.2 that was released today there is a new functionality that is enabling creation of custom templates. I'll be happy to get your feedback!

Best regards,
Dimitar

**Comment by morreau** [comment]
amazing, wonderful you want to open source i want to translate it to dutch

**Comment by jacob2826** [comment]
Plus one, looking forward to @mitenmit open-sourcing the javascript code so others can translate or add extra functionality.

**Comment by mitenmit** [comment]
@harshkumarchourasia @morreau @jacob2826 
Thank you for the interest, the source is published :)

**Comment by morreau** [comment]
Thank you so much Dimitar... I will dive in.
