### ISSUE TITLE
The line brake element inserting menu option

### ISSUE THREAD

**Issue by AntanasPliauskys** [mitenmit/gpt#3]
Excellent work. Man, your code is going viral. 

One notice. When editing a template and inserting a menu option, after pressing Enter, the new option is inserted with the line brake <br> element.

![2024-02-21 102657](https://github.com/mitenmit/gpt/assets/151831878/16d9181f-36db-4586-a60e-afc1e0a32fa7)

**Comment by mitenmit** [comment]
@AntanasPliauskys Thank you for posting this issue, it should be fixed now.
